### PR TITLE
Phase 4: Tool-call connector instance routing

### LINKED ISSUE #962: Support multiple instances of the same connector type per agent
## Context

Today an agent can have at most one Slack, one Google, one GitHub, etc. — the constraint is enforced by `UNIQUE (agent_id, connector_id)` on `agent_connector_credentials` (migration `20260313104413`) and by the composite PK on `agent_connectors`. Users want to attach N instances of the same connector type to a single agent (e.g. 5 Slack workspaces).

We've already lifted the one-per-provider limit on `oauth_connections` (migration `20260313201757`) — this issue extends the same shape to agent-connector bindings end-to-end.

## Recommended approach

Add a surrogate `connector_instance_id UUID` + human `label` on `agent_connectors`. Backfill one default instance per existing (agent, connector) pair so Day 1 matches Day 0. The action type string (`slack.send_message`) does **not** change. Agents pick an instance by passing an optional `connector_instance` parameter (label or UUID); the server resolves it and freezes the UUID + label into the approval's `action` JSON so approvers (web, mobile, future CLI) see which workspace is targeted. New `/instances` sub-routes coexist with the existing `/credential` routes, which are repointed to the default instance for BC.

### Key decisions

- **Instance selection is a parameter, not a new tool name.** Preserves stable `action_type` strings that standing approvals, `action_configurations`, and `Registry.GetAction`'s dot-split all depend on. The capabilities endpoint lists each agent's instance labels in the tool description so the LLM picks by label naturally.
- **Omission rules:** 0 instances → existing "no credential assigned" error; 1 instance → auto-select (BC); 2+ → 400 `connector_instance_required` with `available_instances: [labels...]`.
- **Approval payload:** `_connector_instance_id` + `_connector_instance_label` are stashed at the top level of the existing `action` JSONB. No `approvals` schema change.
- **Standing approvals:** nullable `connector_instance_id` column. NULL = type-wide (legacy), non-null = instance-scoped.
- **No feature flag.** One deploy is safe: backfill ensures old code + new schema both work.

## Data model sketch

**`agent_connectors`**
- Add `connector_instance_id uuid NOT NULL DEFAULT gen_random_uuid()`
- Add `label text NOT NULL` with `UNIQUE (agent_id, connector_id, label)`
- Add `is_default bool NOT NULL DEFAULT false` with partial unique `UNIQUE (agent_id, connector_id) WHERE is_default`
- New PK: `(agent_id, approver_id, connector_id, connector_instance_id)`

**`agent_connector_credentials`**
- Add `connector_instance_id uuid NOT NULL`, backfill from matching `agent_connectors` row
- Repoint FK to the new triple, replace `idx_agent_connector_credentials_unique` with `UNIQUE (agent_id, connector_id, connector_instance_id)`

**`standing_approvals`**
- Add nullable `connector_instance_id uuid` + partial index. Matching filter: `connector_instance_id IS NULL OR connector_instance_id = $n`.

**`approvals`** — no schema change (reserved `_connector_instance_id` / `_connector_instance_label` keys inside the `action` JSONB).

---

## Phase 1 — Schema + backfill

Migrations only. Observable no-op because every agent still has exactly one default instance after backfill.

### Developer

- [ ] `make migrate-create NAME=add_connector_instance_id_to_agent_connectors` — UUID + label + is_default + PK swap + backfill (label defaults to `connectors.name`, first row per pair gets `is_default=true`)
- [ ] `make migrate-create NAME=agent_connector_credentials_fk_to_instance` — add column, backfill from `agent_connectors`, drop old FK + unique index, add triple FK + new unique index
- [ ] `make migrate-create NAME=standing_approvals_add_connector_instance_id` — nullable column + partial index on `(agent_id, action_type, status, connector_instance_id)`
- [ ] Confirm RLS: `TestAppBackendHasPoliciesOnAllRLSTables` and `TestMigrationTimestampsUnique` pass (no new policies needed since `app_backend_all` is FOR ALL)
- [ ] Update `supabase/seed.sql` so the seed runs clean against the new schema

### Manual Testing

- [ ] Run migrations against a seeded dev DB; verify every pre-existing `agent_connectors` row ends up with `connector_instance_id`, `label = connector.name`, `is_default = true`
- [ ] Invariant check: `SELECT COUNT(*) FROM agent_connector_credentials` equals `SELECT COUNT(DISTINCT (agent_id, connector_id)) FROM agent_connector_credentials` after backfill
- [ ] Existing `GET /agents/{id}/connectors` and `/credential` routes return the same data they did pre-migration

---

## Phase 2 — Backend instance CRUD

Depends on Phase 1. New DB helpers + new API routes. Frontend unchanged; agents still only see the default instance until Phase 4.

Items below can run in parallel within the phase.

### Developer

- [ ] New file `db/agent_connector_instances.go`: `CreateAgentConnectorInstance`, `ListAgentConnectorInstances`, `GetAgentConnectorInstance`, `RenameAgentConnectorInstance`, `DeleteAgentConnectorInstance`, `ResolveAgentConnectorInstance(selector)` (accepts UUID or label), `GetDefaultAgentConnectorInstance`
- [ ] `db/agent_connector_credentials.go`: add `*ByInstance` variants of Get/Upsert/Delete; mark `GetAgentConnectorCredential` as `// Deprecated` and have it resolve via default instance
- [ ] `db/standing_approvals.go`: extend struct with `ConnectorInstanceID *string`; append to scans/inserts; update auto-approve match filter
- [ ] New file `api/agent_connector_instances.go`: routes `GET/POST /agents/{id}/connectors/{connector_id}/instances`, `GET/PATCH/DELETE /instances/{instance_id}`, per-instance `/credential`, `/channels`, `/calendars`, `/users`. Register via `RegisterRouteGroup` in `init()` — do NOT edit `api/agent_connectors.go:43-50`
- [ ] Repoint legacy handlers in `api/agent_connectors.go` (`handleAssignAgentConnectorCredential`, `handleRemoveAgentConnectorCredential`, `handleGetAgentConnectorCredential`, channels/calendars/users handlers) to target the default instance via `GetDefaultAgentConnectorInstance`
- [ ] New error codes in `api/error_codes.go`: `ErrConnectorInstanceRequired`, `ErrConnectorInstanceNotFound` (append to end; don't reorder)
- [ ] OpenAPI spec: new `spec/openapi/components/paths/agent_connector_instances.yaml` + schemas file; append refs at end of root spec; mark legacy `/credential` routes as deprecated in their descriptions
- [ ] Regenerate frontend types: `cd frontend && npm run generate:api` and commit
- [ ] Tests: new `db/agent_connector_instances_test.go`, new `api/agent_connector_instances_test.go`, extend `db/agent_connectors_query_test.go` + `db/standing_approvals_test.go`

### Manual Testing

- [ ] Create a 2nd Slack instance on an agent via the new route; confirm both instances appear in `ListAgentConnectorInstances` with distinct UUIDs and labels
- [ ] Confirm legacy `GET/PUT/DELETE /agents/{id}/connectors/{connector_id}/credential` still targets the default instance on a multi-instance agent
- [ ] Rename an instance; confirm unique-label collision returns 409
- [ ] Delete a non-default instance; confirm FK cascade removes its credential binding and instance-scoped standing approvals are revoked

---

## Phase 3 — Frontend UI

Depends on Phase 2. Users can add/remove/rename instances in the dashboard. Agents still use the default instance until Phase 4.

Items below can run in parallel within the phase.

### Developer

- [x] New hooks (append-only — don't edit existing hooks): `useAgentConnectorInstances`, `useAgentConnectorInstanceCredential`, `useCreateAgentConnectorInstance`, `useRenameAgentConnectorInstance`, `useDeleteAgentConnectorInstance`
- [x] New component `frontend/src/pages/agents/connectors/ConnectorInstancesSection.tsx`: cards per instance with label (inline-edit), credential binding (reuse `ConnectorCredentialsSection` patterns), "Make default", "Disconnect"; "+ Add another" button at the bottom
- [x] `ConnectorConfigPage.tsx`: one-line swap `<ConnectorCredentialsSection />` → `<ConnectorInstancesSection />`
- [x] `DisableConnectorSection`: warn "This will remove N instances" in the confirmation dialog
- [x] Storybook: update any stories that render `ConnectorCredentialsSection` to reflect the new multi-instance layout (per CLAUDE.md storybook parity rules)
- [x] Tests: `ConnectorInstancesSection.test.tsx` (create/rename/delete/set-default); `useAgentConnectorInstances.test.ts`; update `ConnectorConfigPage.test.tsx` mocks to return one default instance

### Manual Testing

- [x] Connect a 2nd Slack via the UI using a distinct OAuth account; confirm both appear as cards
- [x] Rename, change default, disconnect individual instances; confirm each action hits the correct instance
- [x] Disable the entire connector type; confirm the warning enumerates all N instances and disabling removes them all
- [x] Visual regression: single-instance agents (today's users) see essentially the same UI as before (one card, no clutter)

---

## Phase 4 — Tool-call instance routing

Depends on Phases 1–3. This is the phase that actually lets an agent use multiple instances.

### Developer

- [x] `api/agent_approvals.go` ingestion (after line 205, before line 211): extract `connector_instance` from `actionObj["parameters"]`, resolve via `db.ResolveAgentConnectorInstance`, enforce 0/1/N rules, strip the param before schema validation, write `_connector_instance_id` + `_connector_instance_label` to `actionObj` top-level, re-marshal `req.Action`
- [x] `api/agent_approvals.go:236`: pass resolved `connectorInstanceID` into `tryStandingApprovalAutoApprove` so matching respects instance scope (`connector_instance_id IS NULL OR = $n`)
- [x] `api/agent_approvals.go:275, 435, 440`: thread `connectorInstanceID` through `resolveCredentialsForResolver` and into the updated `resolveCredentialsWithFallback`
- [x] `api/connector_execution.go:244`: change signature of `resolveCredentialsWithFallback` to include `connectorInstanceID string`; empty string → default instance (BC); swap `GetAgentConnectorCredential` → `GetAgentConnectorCredentialByInstance`; update `executeConnectorAction` caller in the same file
- [x] `api/agent_approvals.go:450-460`: extend `emitApprovalRequestAuditEvent` to pull `_connector_instance_id` + `_connector_instance_label` out of `appr.Action` into audit event meta
- [x] `db/capabilities.go`: add `DISTINCT`/`GROUP BY c.id` to the connector query (avoid duplicate rows per connector when multiple instances exist); add a 5th query returning `(connector_id, connector_instance_id, label, credentials_ready)` per instance; populate a new `Instances` slice on `AgentCapabilities`
- [x] `api/capabilities.go`: add optional `instances: [{id, label, credentials_ready}]` to `connectorCapability`; add optional `connector_instance_id` to `standing_approval_capability`; keep type-level `credentials_ready` = "any instance ready"
- [x] Approval-label rendering helper (shared shape):
  - [x] `frontend/src/pages/dashboard/ReviewApprovalDialog.tsx`: render "Slack (Engineering)" when `action._connector_instance_label` is present; fall through to existing render when absent (BC for pre-migration approvals)
  - [x] `mobile/src/screens/approvals/ApprovalDetailScreen.tsx`: same helper, same fallback
- [x] OpenAPI spec: add `connector_instance` parameter to `POST /agents/{id}/approvals` action parameters docs; add `instances` and `connector_instance_id` to capabilities response schemas; regenerate types
- [x] Integration test `api/approval_flow_multi_instance_test.go`: seed agent with two Slack instances bound to two distinct OAuth connections; submit `slack.send_message` with `connector_instance: "Sales"`; approve; assert Sales OAuth token is the one used (mock Slack client assertion)
- [x] Extend `api/agent_approvals_test.go`: 2+ instances without `connector_instance` → 400 with `connector_instance_required` + `available_instances`; with label → stored approval carries frozen UUID + label
- [x] Extend `api/connector_execution_test.go`: two instances, two OAuth connections, correct one resolved via action JSON instance ID

### Manual Testing

- [x] Agent with a single Slack still works without specifying `connector_instance` (BC)
- [x] Agent with two Slacks without `connector_instance` gets a 400 listing both labels
- [x] Agent with two Slacks passing `connector_instance: "<label>"` routes the action to the correct workspace (verify the message lands in the right Slack)
- [x] Approval dialog (web + mobile) shows "Slack (Engineering)" — not just "Slack" — when approving a multi-instance action
- [x] Instance-scoped standing approval auto-approves only for its instance; actions targeting the other instance still create a pending approval
- [x] Audit log for a multi-instance action includes the instance label
- [x] `permission-slip capabilities` CLI output (raw JSON dump) now includes the `instances` array per connector; old CLI builds still parse the response fine

---

## Rollout & risk

- Single deploy is safe — backfill guarantees that every old (agent, connector) pair has exactly one default instance, so old code running briefly against the new schema returns the same binding via the default. New code without the migration fails hard (`connector_instance_id` column missing); goose auto-runs on boot, so migration-first ordering is inherent.
- Disabling a connector type removes all N instances — the existing `DisableAgentConnector` query at `db/agent_connectors.go:138` already deletes all rows matching `(agent_id, approver_id, connector_id)`, and with the new PK that nukes every instance. Surface this clearly in the UI confirmation.
- Instance-scoped standing approvals must be revoked when their instance is deleted — application-level cleanup inside `DeleteAgentConnectorInstance`, mirroring the existing revocation pattern in `DisableAgentConnector`.

## Critical files

- Migrations: three new files via `make migrate-create`
- `db/agent_connector_instances.go` (new)
- `db/agent_connector_credentials.go`
- `db/standing_approvals.go`
- `db/capabilities.go`
- `api/agent_connector_instances.go` (new)
- `api/connector_execution.go` (`resolveCredentialsWithFallback` signature)
- `api/agent_approvals.go` (ingestion + forwarding + audit)
- `api/capabilities.go` (additive fields)
- `spec/openapi/components/paths/agent_connector_instances.yaml` (new) + schemas file
- `frontend/src/pages/agents/connectors/ConnectorInstancesSection.tsx` (new)
- `frontend/src/pages/agents/connectors/ConnectorConfigPage.tsx` (one-line swap)
- `frontend/src/pages/dashboard/ReviewApprovalDialog.tsx`
- `mobile/src/screens/approvals/ApprovalDetailScreen.tsx`

### PR DESCRIPTION
**Pull request by chiedocursor**
## Summary

Implements GitHub issue #962 Phase 4: agents can target a specific connector instance via `action.parameters.connector_instance` (label or UUID). The server strips it before schema validation, freezes `_connector_instance_id` / `_connector_instance_label` on the stored action JSON, and routes credentials + standing-approval matching accordingly.

Also extends capabilities with per-instance rows (`instances[]`), threads instance scope through execution paths, enriches approval-request audit metadata, and updates web + mobile approval UIs to show `Connector (Label)` when a frozen label exists.

## Test plan

- [x] `cd frontend && npx vitest run src/pages/dashboard/approvalConnectorLabel.test.ts`
- [x] `cd mobile && npm test -- --ci src/screens/approvals/__tests__/approvalUtils.test.ts`
- [ ] Backend: `make test-backend` — **not run in this environment** (local Go version mismatch vs `go.mod`; CI should run full suite)

Closes #962

<div><a href="https://cursor.com/agents/bc-9e6ab8f7-c0d0-4bbe-8fc4-be0ffa6e989a"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/assets/images/open-in-web-dark.png"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/assets/images/open-in-web-light.png">Open in Web</picture></a>&nbsp;<a href="https://cursor.com/background-agent?bcId=bc-9e6ab8f7-c0d0-4bbe-8fc4-be0ffa6e989a"><picture><source media="(prefers-color-scheme: dark)" srcset="https://cursor.com/assets/images/open-in-cursor-dark.png"><source media="(prefers-color-scheme: light)" srcset="https://cursor.com/assets/images/open-in-cursor-light.png">Open in Cursor</picture></a>&nbsp;</div>

### CODE REVIEW

**Comment by chiedocursor** [comment]
## 🤖 Watch Session Summary

### Changes Made
No changes made during this session.

### Decision Log

#### ✅ Implemented
No review comments acted on.

---
*Watch session ended after 0 minutes of inactivity. Processed 0 comments across 1 poll cycles.*

## 🔧 CI / audit remediation

### Remediation round 1

- **ci.yml** — conclusion `failure` — api/approval_flow_multi_instance_test.go used http.MethodPost and http.StatusOK without importing net/http; added import net/http. (`cf6a74d9`)

### Remediation round 2

- **ci.yml** — conclusion `failure` — Tests failed: duplicate credentials (user_id,service,label) when two vault credentials shared service without labels; added InsertCredentialWithVaultSecretIDAndLabel. Multi-instance approval test: parameters key omitted when empty after stripping connector_instance — assert only when parameters present. (`4337602a`)

File: api/agent_approvals_instance.go [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+	if raw, ok := actionObj["parameters"]; ok && len(raw) > 0 && string(raw) != "null" {
+		if err := json.Unmarshal(raw, &paramsObj); err != nil {
+			return "", err
+		}
+	}
+
+	var selector string
+	if paramsObj != nil {
+		if raw, ok := paramsObj["connector_instance"]; ok {
+			_ = json.Unmarshal(raw, &selector)
```
Comment (chiedoclaude) [inline api/agent_approvals_instance.go:43]: **[Medium · Correctness]** The error from `json.Unmarshal(raw, &selector)` is discarded, so any non-string value for `connector_instance` (number, bool, null, array, object) silently becomes an empty selector.

**Why:** In the single-instance case the agent is then quietly routed to the only instance; in the multi-instance case the agent gets a `connector_instance_required` error *even though they provided the field*. Both are confusing — the agent sees a misleading error (or unexpected behavior) instead of a clear "`connector_instance` must be a string" message.

**Fix:** Type-check and return a validation error when the value is present but not a JSON string:

```go
if raw, ok := paramsObj["connector_instance"]; ok {
    if err := json.Unmarshal(raw, &selector); err != nil {
        return "", &connectorInstanceResolutionError{
            status: http.StatusBadRequest,
            resp:   BadRequest(ErrInvalidRequest, "connector_instance must be a string (instance label or UUID)"),
        }
    }
    selector = strings.TrimSpace(selector)
    delete(paramsObj, "connector_instance")
    // …rest unchanged
}
```

File: api/agent_approvals.go [hunk 2]
```diff
@@ -204,6 +204,23 @@ func handleAgentRequestApproval(deps *Deps) http.HandlerFunc {
...
+				return
+			}
+			log.Printf("[%s] applyConnectorInstanceToAction: %v", TraceID(r.Context()), err)
+			CaptureError(r.Context(), err)
+			RespondError(w, r, http.StatusInternalServerError, InternalError("Failed to process action"))
+			return
+		}
+		if updated, mErr := json.Marshal(actionObj); mErr == nil {
+			req.Action = updated
+		}
```
Comment (chiedoclaude) [inline api/agent_approvals.go:222]: **[Medium · Reliability]** `json.Marshal(actionObj)` error is silently swallowed here. If marshal fails after `applyConnectorInstanceToAction` has frozen `_connector_instance_id` and `_connector_instance_label` on the map, `req.Action` keeps the *original* action JSON — so the approval is stored without the frozen fields and without the stripped `connector_instance`, defeating the whole routing contract.

**Why:** Later, `executeApprovalAction` reads `_connector_instance_id` from the stored action and falls back to the default-instance credential when it's missing — so a silent marshal failure here means the wrong credential could be used at execution time, with no log trail pointing at the cause.

**Fix:** Treat the marshal error as a 500 (like `applyConnectorInstanceToAction`'s own errors):

```go
updated, mErr := json.Marshal(actionObj)
if mErr != nil {
    log.Printf("[%s] re-marshal action after connector_instance apply: %v", TraceID(r.Context()), mErr)
    CaptureError(r.Context(), mErr)
    RespondError(w, r, http.StatusInternalServerError, InternalError("Failed to process action"))
    return
}
req.Action = updated
```

In practice `json.Marshal` on a `map[string]json.RawMessage` rarely fails, but the cost of defending against it is trivial and the cost of a silent miscredential at runtime is not.

File: api/approvals.go [hunk 3]
```diff
@@ -251,7 +251,17 @@ func executeApprovalAction(ctx context.Context, deps *Deps, userID string, appr
...
-	result, execErr := executeConnectorAction(ctx, deps, appr.AgentID, userID, actionType, actionObj.Parameters, nil)
+	var connectorInstanceID string
+	if len(appr.Action) > 0 {
+		var raw map[string]json.RawMessage
+		if json.Unmarshal(appr.Action, &raw) == nil {
+			if v, ok := raw["_connector_instance_id"]; ok {
+				_ = json.Unmarshal(v, &connectorInstanceID)
+			}
+		}
+	}
```
Comment (chiedoclaude) [inline api/approvals.go:262]: **[Low · Maintainability]** `appr.Action` is unmarshaled twice — once into the `actionObj` struct above (for `Parameters`), and again here into a `map[string]json.RawMessage` just to read `_connector_instance_id`.

**Why:** Two parses of the same JSON is wasteful and the split logic is easy to drift — e.g., a future reviewer adding another frozen field (`_connector_instance_label`) will naturally add it next to `_connector_instance_id` and miss that `actionObj` is a separate decode.

**Fix:** Parse once into a map and read both `parameters` and `_connector_instance_id` from it:

```go
var raw map[string]json.RawMessage
if len(appr.Action) > 0 {
    _ = json.Unmarshal(appr.Action, &raw)
}
var parameters json.RawMessage
if v, ok := raw["parameters"]; ok {
    parameters = v
}
var connectorInstanceID string
if v, ok := raw["_connector_instance_id"]; ok {
    _ = json.Unmarshal(v, &connectorInstanceID)
}

result, execErr := executeConnectorAction(ctx, deps, appr.AgentID, userID, actionType, parameters, nil, connectorInstanceID)
```

File: api/agent_approvals_instance.go [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+				resp:   BadRequest(ErrConnectorInstanceNotFound, "no connector instance matches the given connector_instance"),
+			}
+		}
+		inst = resolved
+	}
+
+	idRaw, _ := json.Marshal(inst.ConnectorInstanceID)
+	actionObj["_connector_instance_id"] = idRaw
+	labelRaw, _ := json.Marshal(inst.Label)
+	actionObj["_connector_instance_label"] = labelRaw
```
Comment (chiedoclaude) [inline api/agent_approvals_instance.go:110]: **[Low · Maintainability]** `inst.Label` is marshaled unconditionally, so if an instance somehow ends up with an empty label (extension/migration edge cases, future code paths that bypass `CreateAgentConnectorInstance`'s required-label check), you'll freeze `"_connector_instance_label": ""` into the stored action and the audit event.

**Why:** Both `redactActionToTypeWithConnectorInstance` and the mobile/web label readers already skip empty strings, so the empty value is never rendered — which means it's pure noise in stored JSON and audit output.

**Fix:** Only set the label field when it's non-empty:

```go
idRaw, _ := json.Marshal(inst.ConnectorInstanceID)
actionObj["_connector_instance_id"] = idRaw
if inst.Label != "" {
    labelRaw, _ := json.Marshal(inst.Label)
    actionObj["_connector_instance_label"] = labelRaw
}
return inst.ConnectorInstanceID, nil
```

Today the DB-level `CreateAgentConnectorInstance` already rejects empty labels, so this is defensive — but it makes the invariant self-documenting.

File: api/agent_approvals_instance.go [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+			if err != nil {
+				return "", err
+			}
+			if resolved == nil || resolved.ConnectorInstanceID != only.ConnectorInstanceID {
+				return "", &connectorInstanceResolutionError{
+					status: http.StatusBadRequest,
+					resp:   BadRequest(ErrConnectorInstanceNotFound, "no connector instance matches the given connector_instance"),
+				}
+			}
+			inst = resolved
```
Comment (chiedoclaude) [inline api/agent_approvals_instance.go:82]: **[Low · Simplicity]** In the `len(instances) == 1` + selector path, you already have `only` in hand — going back through `ResolveAgentConnectorInstance` (which re-queries the DB by UUID or label) just to compare the returned ID against `only.ConnectorInstanceID` adds a round-trip that can only produce `only` or `nil`.

**Why:** It's an avoidable DB hit on the hot path (every single-instance approval request with a selector), and the extra `!=` check is dead code once you realize the function can't return any other instance.

**Fix:** Compare directly against the one instance you have:

```go
if len(instances) == 1 {
    only := &instances[0]
    if selector == "" || selector == only.ConnectorInstanceID || selector == only.Label {
        inst = only
    } else {
        return "", &connectorInstanceResolutionError{
            status: http.StatusBadRequest,
            resp:   BadRequest(ErrConnectorInstanceNotFound, "no connector instance matches the given connector_instance"),
        }
    }
}
```

(Only keep the `uuid.Parse` tolerance if callers might pass a non-canonical UUID form; `ResolveAgentConnectorInstance`'s behavior suggests callers already pass canonical form.)

**Review by chiedoclaude — COMMENTED** [review]
## Review Round 1/6

**Findings:** 5 (0 critical, 0 high, 2 medium, 3 low)

The overall design is sound: the `parameters.connector_instance` selector is resolved once at approval-request time, the UUID+label are frozen on the stored action JSON, and every downstream execution path (standing-approval auto-approve, pending-approval approve, user-initiated SA execution, resource-detail resolver) now threads the instance ID through credential resolution. Test coverage is thorough — the `TestApprovalFlow_MultiInstance_UsesCorrectCredentialOnApprove` end-to-end test in particular gives good confidence that the right credential actually reaches the connector at execution time.

The findings I posted inline are around robustness: the selector parsing silently coerces non-string inputs, the re-marshal error is swallowed after freezing fields, and a couple of small maintainability items. Nothing blocking.

### Additional observations (non-inline)

- **Audit-event consistency:** `api/approvals.go:496` still calls `redactActionToType` for the `approval.approved` / `approval.denied` / `approval.cancelled` events, while `approval.requested` now uses `redactActionToTypeWithConnectorInstance`. For admins investigating which instance actually ran, it'd be useful to switch the approve/deny/cancel paths over to the new helper too so the frozen instance ID/label appears on every approval-lifecycle event, not just request. That line isn't in the diff so I couldn't inline this. Severity: **Low**.
- **Web/mobile helper duplication:** `connectorInstanceLabelFromAction` lives in `mobile/src/screens/approvals/approvalUtils.ts`, while the web (`ReviewApprovalDialog.tsx`) reinvents the same extraction inline with a verbose `typeof … in … as …` ladder. If these ever diverge (e.g., supporting a localized label field), you'll fix it in two places. Not blocking, but consider extracting a shared helper. Severity: **Low**.
- **Capabilities query shape:** The per-connector `BOOL_OR(NOT EXISTS(...))` in `db/capabilities.go` correlates only on `ac.agent_id` / `c.id`, not on `ac.connector_instance_id`, so BOOL_OR evaluates the same predicate for every row in the group. That's fine (it's just a wrapper needed by GROUP BY), but the code will read more clearly if it uses a simple `MAX(CASE…) = 1` or drops the redundant OR. Severity: **Low** (cosmetic).
- **CI / backend tests:** PR body notes that backend tests weren't run locally due to the Go toolchain mismatch. CI needs to be green before merging — the changes cross a lot of hot paths (credential resolution, standing-approval matching, audit events).

### What Looks Good

- Excellent test coverage: multi-instance required, label freeze, stripping, per-instance execution, and a full request→approve→execute E2E with distinct credentials.
- Clean separation: the new `applyConnectorInstanceToAction` lives in its own file (`api/agent_approvals_instance.go`), keeping the main handler readable.
- The `_connector_instance_*` frozen fields are a nice design — they decouple approval storage from runtime agent-connector state, so deleting/relabeling an instance after approval doesn't corrupt historical records.
- OpenAPI updates are in sync with the code (`ApprovalSummary.action.allOf` extension, `ConnectorInstanceCapability`, `StandingApprovalCapability.connector_instance_id`, plus the long-form `Action` description explaining the selector behavior).
- `resolveCredentialsForConnectorInstance` cleanly becomes a one-liner delegating to `resolveCredentialsWithFallback` — nice DRY win.

---
*Automated review by `/review` — Round 1 of 6*

**Comment by chiedoclaude** [comment]
## Code Review Complete

**PR:** #967 — Phase 4: Tool-call connector instance routing
**Author:** @chiedocursor
**Rounds completed:** 5/6
**Reason for stopping:** PR merged

### Outstanding Issues

5 findings from Round 1 remained open at merge time (none critical/high). For follow-up consideration:

1. **[Medium · Correctness]** `api/agent_approvals_instance.go:43` — `connector_instance` selector silently coerces non-string values to empty, which then produces misleading "required" errors or silent default-instance routing. Add a type check and return a validation error.
2. **[Medium · Reliability]** `api/agent_approvals.go:221` — `json.Marshal` error on the re-serialized action is swallowed; a silent failure here would store the action without the frozen `_connector_instance_id`/`_connector_instance_label`, and the later execute path would fall back to the default-instance credential with no log trail. Treat it as a 500 and log.
3. **[Low · Maintainability]** `api/approvals.go:247–262` — `appr.Action` is unmarshaled twice (once for parameters, once for the instance ID). Consolidate into a single `map[string]json.RawMessage` decode.
4. **[Low · Maintainability]** `api/agent_approvals_instance.go:109–110` — `_connector_instance_label` is frozen even when empty; guard with `if inst.Label != ""`.
5. **[Low · Simplicity]** `api/agent_approvals_instance.go:72–82` — Single-instance + selector path does an unnecessary DB round-trip via `ResolveAgentConnectorInstance`; compare directly against `only.ConnectorInstanceID` / `only.Label`.

Plus three review-body items (audit-event consistency between `approval.requested` and `approval.approved/denied/cancelled`, web/mobile `connectorInstanceLabelFromAction` duplication, cosmetic simplification of the `BOOL_OR` in the capabilities query).

### Review History

| Round | Inline Comments | Notes |
|-------|-----------------|-------|
| 1 | 5 | Initial review — 2 medium, 3 low findings, plus 3 additional body notes |
| 2 | 0 | New commit added missing `net/http` import in multi-instance E2E test (CI fix) — no source changes, no new findings |
| 3 | 0 | New commit disambiguated test credential fixtures and handled absent `parameters` key after strip — test-only, no source changes, no response to Round 1 findings |
| 4 | 0 | No new commits, no new findings |
| 5 | 0 | PR merged before any fixes to Round 1 feedback |

### Overall Assessment

The architecture of Phase 4 is well thought out: resolving the `connector_instance` selector once at request time and freezing `_connector_instance_id`/`_connector_instance_label` on the stored action JSON is the right approach — it decouples the approval record from mutable agent-connector state and gives every downstream execution path (standing auto-approve, pending approve, user-initiated SA execute, resource-detail resolver) a single authoritative source for routing. Test coverage is strong, especially the end-to-end fixture that verifies the correct credential actually reaches the connector on approve.

The open findings are all polish rather than correctness blockers: stricter input validation for the selector, logging the one Marshal failure mode, and a few cleanups. Worth addressing in a follow-up PR so the edges of the contract are as tight as the happy path.

---
*Review performed by Claude Code `/review` skill*
